spring.application.name=VMD-webshop


# MySQL Configuration

spring.datasource.url=jdbc:mysql://89.150.155.236:3306/VMD
spring.datasource.username=Nikolaj
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA Configuration # Use 'update' for development and 'none' for production
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Configuration
file.img-upload-dir=src/main/resources/images/

