spring.application.name=VMD-webshop


# MySQL Configuration

spring.datasource.url=jdbc:mysql://89.150.155.236:3306/VMD
spring.datasource.username=Emil
spring.datasource.password=6c73EHVemW3E7BpbH
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA Configuration # Use 'update' for development and 'none' for production
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Configuration
file.img-upload-dir=src/main/resources/images/

# Website
website.domain=http://localhost:8080

#Stripe
stripe.SecretKey=pk_test_51QNXSjKce2p6JuwHdLwNmZr6fmFa9s0lZPKsAiV37gadJGkeDsqJuGf1jUPXu63qkBm7UMRstWyg3i3qmc8F5WLO00ouEYbgAX
